[build]
  cmd = "go build -o tmp/main.exe ./cmd"
  entrypoint = ["tmp/main.exe"]
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  kill_delay = "2s"
[env]
  DATABASE_URL = "postgres://postgres:postgres@localhost:5432/pulse?sslmode=disable"